CREATE TABLE task (
  id MEDIUMINT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userName VARCHAR(30) NOT NULL,
  userEmail VARCHAR(255) NOT NULL,
  taskText TEXT NOT NULL,
  isCompleted TINYINT(1) UNSIGNED,
  isEdited TINYINT(1) UNSIGNED
);
